### ISSUE TITLE
repl: ^D leaves console in raw mode

### ISSUE THREAD

**Issue by bnoordhuis** [saghul/quv#18]
```
$ ./quv 
Welcome to quv — QuickJS + libuv
Type "\h" for help
> ^D
^D
```
The first ^D does nothing (or does it?), the second one terminates the process but leaves the console in raw mode.

**Comment by bnoordhuis** [comment]
FWIW, this patch fixes the issue for me although that `return -3;` is probably there for a reason.
```diff
diff --git a/src/repl.js b/src/repl.js
index 7b95ff4..71ee19f 100644
--- a/src/repl.js
+++ b/src/repl.js
@@ -411,7 +411,7 @@ import * as uv from "uv";
     function control_d() {
         if (cmd.length == 0) {
             stdout.write("\n");
-            return -3; /* exit read eval print loop */
+            exit(0);
         } else {
             delete_char_dir(1);
         }
```

**Comment by saghul** [comment]
Hum, looks like -3 is handled by just removing the SIGINT signal handler here: https://github.com/saghul/quv/blob/13ba7a881e7d677949e6210fa3dccb9c86ef4b8d/src/repl.js#L814

Not sure what does is supposed to accomplish TBH. Your proposed fix LGTM, care to send it as a PR? Thank you!

**Comment by saghul** [comment]
Looking at it again (in the original code) it also removed the read handler, which I think caused the loop to exit because there is nothing more to do. So I think this pretty much means your fix is right. Since you're there, care to remove that `case -3`? :-)
