### ISSUE TITLE
object leaks

### ISSUE THREAD

**Issue by xiaoweime** [saghul/quv#59]
(async () => {
    const res = await fetch('http://www.baidu.com');
    console.log(res);
})();

quv: ./quv/deps/quickjs/src/quickjs.c:1643: JS_FreeRuntime: Assertion `list_empty(&rt->obj_list)' failed.

**Comment by xiaoweime** [comment]
var xhr = new XMLHttpRequest()
xhr.onload = function(e) {
     console.log(xhr.responseText);
}
xhr.open('GET', 'http://www.baidu.com')
xhr.send()

**Comment by saghul** [comment]
I could reproduce this, thanks for the report!
